(feature) Delete project data partially
Swetrix/swetrix-api pull request #109
Opened 2023-02-25 22:08 UTC by Blaumaus

2023-02-25 22:08 UTC, kruzhambus approved these changes

2023-02-27 21:50 UTC, yevheniikulisidi requested changes

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +  @Roles(UserType.CUSTOMER, UserType.ADMIN)
You can use `@Auth([UserType.CUSTOMER, UserType.ADMIN])` decorator.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +    }
You can put the validation of the project id in the DTO file.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +    }
You can put the validations in a DTO file.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +    await clickhouse.query(queryP, params).toPromise()
You can use `Promise.all()`.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +    const queryP = 'ALTER TABLE performance DELETE WHERE pid = {pid:FixedString(12)} AND created BETWEEN {from:String} AND {to:String}'
Name more readable query variables like `queryAnalytics` and `queryPerformance`.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +    this.projectService.allowedToManage(project, uid)
Add `await` because you are calling an asynchronous function.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +  @ApiResponse({ status: 201 })
The response code status cannot be `201`, you are deleting data, not creating it. Replace it with `200`.

2023-02-27 21:50 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +  ): Promise<any> {
Do not use the type `any`, as you are destroying the meaning of the language.

2023-03-23 00:35 UTC, merged