(feature) Captcha service
Swetrix/swetrix-api pull request #110
Opened 2023-03-03 00:44 UTC by Blaumaus

2023-03-13 12:56 UTC, yevheniikulisidi requested changes

2023-03-13 12:56 UTC, yevheniikulisidi commented on src/captcha/captcha.controller.ts
> +  @BotDetection()
You can make a combined decorator - https://docs.nestjs.com/custom-decorators#decorator-composition

2023-03-13 12:56 UTC, yevheniikulisidi commented on src/captcha/captcha.service.ts
> +}
The best solution would be to put the interface in a separate file.

2023-03-13 12:57 UTC, ghost commented on src/captcha/captcha.controller.ts
> +const CAPTCHA_COOKIE_KEY = 'swetrix-captcha-token'
A better solution would be to put the constant in a separate file.

2023-03-13 12:57 UTC, ghost commented on src/captcha/captcha.controller.ts
> +  @Get('/auto-verifiable')
You do not have to use `/`.

2023-03-13 13:00 UTC, ghost commented on src/captcha/captcha.controller.ts
> +    const tokenCookie = request?.cookies?.[CAPTCHA_COOKIE_KEY]
Remove `@ts-ignore` and do the typing and checks.

2023-03-13 13:01 UTC, ghost commented on src/captcha/captcha.service.ts
> +}
The best solution would be to put the interface in a separate file.

2023-03-13 13:04 UTC, yevheniikulisidi requested changes

2023-03-13 13:04 UTC, yevheniikulisidi commented on src/captcha/dtos/manual.dto.ts
> +}
Add stricter validation. You can use this table - https://github.com/typestack/class-validator#validation-decorators

2023-03-13 13:07 UTC, yevheniikulisidi commented on src/captcha/dtos/generate.dto.ts
>    theme?: string
More validation!

2023-03-13 13:07 UTC, yevheniikulisidi commented on src/captcha/dtos/validate.dto.ts
>    hash?: string
More validation!

2023-03-13 13:14 UTC, yevheniikulisidi requested changes

2023-03-13 13:14 UTC, yevheniikulisidi commented on src/project/dto/project.dto.ts
> +  isCaptcha: boolean
There is no validation at all.

2023-03-13 13:14 UTC, yevheniikulisidi commented on src/project/entity/project.entity.ts
> +  isCaptchaEnabled: boolean
Add an entity column type.

2023-03-13 13:14 UTC, yevheniikulisidi commented on src/project/project.controller.ts
> +      }
It's just terrible code. No typing, and you can use the conditional operator here.

2023-03-13 13:15 UTC, yevheniikulisidi requested changes

2023-03-13 13:15 UTC, ghost commented on src/project/entity/project.entity.ts
>    isCaptchaEnabled: boolean
Add an entity column type.

2023-03-13 13:16 UTC, ghost commented on src/project/project.controller.ts
> +      console.log(where)
Use logging from Nest.

2023-03-13 13:19 UTC, yevheniikulisidi requested changes

2023-03-13 13:19 UTC, ghost commented on src/captcha/captcha.service.ts
> +
You can check `isManual` and `timestamp` in the function.

2023-03-13 13:19 UTC, ghost commented on src/captcha/dtos/automatic.dto.ts
> +  pid: string
Add validation.

2023-03-13 13:19 UTC, ghost commented on src/captcha/dtos/generate.dto.ts
> +  pid: string
Add validation.

2023-03-13 13:19 UTC, ghost commented on src/captcha/dtos/manual.dto.ts
> +  pid: string
Add validation.

2023-03-13 13:19 UTC, yevheniikulisidi requested changes

2023-03-13 13:19 UTC, yevheniikulisidi commented on src/captcha/dtos/validate.dto.ts
>    secret: string
Add validation.

2023-03-13 13:20 UTC, yevheniikulisidi requested changes

2023-03-13 13:20 UTC, yevheniikulisidi commented on src/project/entity/project.entity.ts
> +  isCaptchaEnabled: boolean
Add an entity column type.

2023-03-13 21:56 UTC, Blaumaus commented on src/captcha/captcha.controller.ts
> +  @BotDetection()
in the future

2023-03-13 22:00 UTC, Blaumaus commented on src/captcha/captcha.controller.ts
> +  @Get('/auto-verifiable')
it's used in other places like project, user, etc. so I'll keep it to preserve code consistency

2023-03-13 22:11 UTC, Blaumaus commented on src/project/entity/project.entity.ts
>    isCaptchaEnabled: boolean
should be done in a separate PR as the `@ApiProperty()` is empty for a lot of places in this and other entities

2023-03-15 13:59 UTC, yevheniikulisidi requested changes
The functions must be inside the `CaptchaService` class.

2023-03-15 14:09 UTC, yevheniikulisidi requested changes

2023-03-15 14:09 UTC, ghost commented on src/project/project.controller.ts
> +  @Roles(UserType.CUSTOMER, UserType.ADMIN)
You can use the `@Auth()` decorator.

2023-03-15 14:09 UTC, ghost commented on src/project/project.controller.ts
> +    @Param('pid') pid: string,
If you use such a code, you expose the route to possible danger. All because you don't put it in a separate DTO file, and you don't validate the data.

2023-03-15 14:09 UTC, ghost commented on src/project/project.controller.ts
> +    }
This should be in the DTO file.

2023-03-15 14:09 UTC, ghost commented on src/project/project.controller.ts
> +    let secret: string = null
It is more correct to `string | null`.

2023-03-21 01:55 UTC, merged