Extension comment system from https://github.com/Swetrix/swetrix-api/pull/104 to new structure
Swetrix/swetrix-api pull request #163
Opened 2023-06-29 18:27 UTC by kruzhambus

PR Checklist:
 - [ ] Your feature / improvement is implemented for Selfhosted version of Swetrix (if applicable)
 - [ ] MySQL / Clickhouse migrations added (if you updated entities)

2023-06-29 18:27 UTC, kruzhambus commented
https://github.com/Swetrix/swetrix-api/pull/104

2023-07-20 20:15 UTC, yevheniikulisidi requested changes

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
>      count: number
you can put it in a separate file

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    comments: Comment[] & { isOwner?: boolean }
and why do you have `isOwner` optional?

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    }
this can be done as a query

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    return _omit(comment, ['userId'])
also by itself, simply by adding the parameter `select: [...]` to the query function

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    }
you can create a separate function with a query for role and access definition

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +  ): Promise<CommentReply & { isOwner?: boolean }> {
and why do you have `isOwner` optional?

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +  }
make it as a query rather than picking it up piecemeal

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    }))
make queries!

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    }
make queries!

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.controller.ts
> +      !(commentReply.userId === userId || _includes(user.roles, UserType.ADMIN))
make a separate function for defining user roles

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.service.ts
> +      throw new NotFoundException('Comment not found')
It is better not to make exceptions in services. there should be logic in them, so move them to the controller

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/comments.service.ts
> +    }
make a separate function to check

2023-07-20 20:15 UTC, ghost commented on apps/production/src/marketplace/comments/comments.service.ts
> +    }
move the exceptions to the controller!

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/bodies/create-comment.dto.ts
> +  reply: string | null
how is this a reply without a comment? 😁

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/bodies/create-reply.dto.ts
> +  text: string | null
again a reply with no comment? 😏

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/bodies/update-reply.dto.ts
> +  text: string | null
do not repeat a field again if it has already been repeated somewhere. use [mapped types](https://docs.nestjs.com/openapi/mapped-types#pick)

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/params/get-comment.dto.ts
>    commentId: string
add the `@IsUUID()` decorator.

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/params/delete-comment.dto.ts
>    commentId: string
add the `@IsUUID()` decorator.

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/queries/create-comment.dto.ts
>    userId: string
add the `@IsUUID()` decorator.

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/queries/get-comments.dto.ts
> +  extensionId: string
add the `@IsUUID()` decorator.

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/dtos/queries/get-comments.dto.ts
> +  userId?: string
add the `@IsUUID()` decorator.

2023-07-20 20:15 UTC, yevheniikulisidi commented on apps/production/src/marketplace/comments/entities/comment-reply.entity.ts
> +}
you can add the `updatedAt` field, might come in handy

2023-07-20 20:23 UTC, kruzhambus commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    comments: Comment[] & { isOwner?: boolean }
Because fe dev need it and we use it to not return userId

2023-07-20 20:25 UTC, kruzhambus commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    }
Okay

2023-10-21 15:46 UTC, Blaumaus commented on apps/production/src/marketplace/comments/comments.controller.ts
> +    return _omit(comment, ['userId'])
нам потрібен userId для перевірок вище, але віддавати його на фронтенд немає сенсу, тому залишаю _omit

2023-10-21 15:49 UTC, Blaumaus commented on apps/production/src/marketplace/comments/dtos/bodies/create-reply.dto.ts
> +  text: string | null
^^ `commentId`

2023-10-21 15:51 UTC, Blaumaus approved these changes
lgtm

2023-10-21 15:51 UTC, merged