(improvement) Plan limit
Swetrix/swetrix-api pull request #211
Opened 2024-02-10 19:23 UTC by Borfak

Please describe your changes using the checklist below.

### Self-hosted support
- [ ] Your feature is implemented for the selfhosted version of Swetrix
- [ ] This PR only updates the production code (e.g. paddle webhooks, CAPTCHA, blog, etc.)

### Database migrations
- [ ] Clickhouse / MySQL migrations added for this PR
- [ ] No table schemas changed in this PR

### Documentation
- [ ] You have updated the [documentation](https://github.com/swetrix/docs) according to your PR
- [ ] This PR did not change any publicly documented endpoints

2024-02-10 19:32 UTC, kruzhambus approved these changes
Cool

2024-02-11 19:39 UTC, Blaumaus approved these changes

2024-02-11 19:46 UTC, Blaumaus requested changes
migrations

2024-02-11 19:49 UTC, Blaumaus requested changes
1. Add migrations for new user entity value:
```sql
ALTER TABLE user ADD column `planLimitNotificationPercentage` int NOT NULL DEFAULT '80';
```
2. In user controller (settings update) add an endpoint to update this value. Make sure to do validations that the value provided is:
 - `>=0`
 - `<=100`
 - `% 10 === 0` (i.e. 10, 20, 30, ... only allowed)

2024-02-21 22:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Swetrix/swetrix-api?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Swetrix/swetrix-api?pullRequest=211) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Artem Boichuk<br/>:x: Blaumaus<br/><hr/>**Artem Boichuk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Swetrix/swetrix-api?pullRequest=211) it.</sub>

2024-04-21 14:31 UTC, yevheniikulisidi commented on apps/production/src/user/dto/update-user.dto.ts
> +  planLimitNotificationPercentage: number
Name the field shorter, and add minimal validation.

2024-04-21 14:31 UTC, yevheniikulisidi commented on apps/production/src/user/entities/user.entity.ts
> +  planLimitNotificationPercentage: number
Name a shorter column.

2024-04-21 14:44 UTC, yevheniikulisidi requested changes

2024-04-21 14:44 UTC, yevheniikulisidi commented on apps/production/src/task-manager/task-manager.service.ts
> +            `You've reached ${planLimitNotificationPercentage}% of your monthly event limit.\nThat's a lot of traffic, congratulations!\nThat means that in case you use 100% of the available events u
Add text hyphenation. It's not readable.

2024-07-13 21:37 UTC, Blaumaus commented
Closing as this is not really needed at the moment after the "locked dashboards" update

2024-07-13 21:37 UTC, closed without merging