(feature) Error tracking
Swetrix/swetrix-api pull request #224
Opened 2024-03-30 23:18 UTC by Blaumaus

Please describe your changes using the checklist below.

### Self-hosted support
- [ ] Your feature is implemented for the selfhosted version of Swetrix
- [ ] This PR only updates the production code (e.g. paddle webhooks, CAPTCHA, blog, etc.)

### Database migrations
- [ ] Clickhouse / MySQL migrations added for this PR
- [ ] No table schemas changed in this PR

### Documentation
- [ ] You have updated the [documentation](https://github.com/swetrix/docs) according to your PR
- [ ] This PR did not change any publicly documented endpoints

2024-04-21 14:42 UTC, yevheniikulisidi requested changes

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +
Put the DTO in a separate file.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +
Take the function out to the service.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +    @Ip() reqIP,
Typify!

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +    @Headers() headers: { 'x-password'?: string },
A better way to do it is `@Headers('x-password')`.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +  ): Promise<any> {
If there is no response, replace `any` with `void`.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +    @Headers() headers: { 'x-password'?: string },
A better way to do it is `@Headers('x-password')`.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +  ): Promise<any> {
If there is no response, replace `any` with `void`.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/analytics.controller.ts
> +    this.analyticsService.validatePID(pid)
Pass validation at DTO.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/dto/error.dto.ts
> +}
Add minimal validation.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/dto/get-error.dto.ts
> +  eid: string
Name the field better `errorId`.

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/dto/get-errors.dto.ts
> +  skip: number
Validate it!!!

2024-04-21 14:42 UTC, yevheniikulisidi commented on apps/production/src/analytics/dto/patch-status.dto.ts
> +}
More validation!

2024-05-05 15:24 UTC, Blaumaus commented on apps/production/src/analytics/analytics.controller.ts
> +    this.analyticsService.validatePID(pid)
it will be done in a separate PR because this change requires changing other endpoints out of this PRs scope

2024-05-05 15:24 UTC, Blaumaus commented on apps/production/src/analytics/analytics.controller.ts
> +    @Headers() headers: { 'x-password'?: string },
it will be done in a separate PR because this change requires changing other endpoints out of this PRs scope

2024-05-05 15:25 UTC, Blaumaus commented on apps/production/src/analytics/analytics.controller.ts
> +  ): Promise<any> {
there is response

2024-05-05 15:25 UTC, Blaumaus commented on apps/production/src/analytics/analytics.controller.ts
> +    @Headers() headers: { 'x-password'?: string },
will be done in a separate PR because it changes other functionality as well

2024-05-06 20:24 UTC, merged

2024-05-07 20:35 UTC, bengalaviz commented
Any idea on when this will be available in the docker version?

2024-05-07 21:18 UTC, Blaumaus commented
> Any idea on when this will be available in the docker version?

soon, I promise. I'll fix a few bugs related to timezones first and will start working on a new selfhosted release