(feature) Telegram bot
Swetrix/swetrix-api pull request #92
Opened 2023-01-01 20:17 UTC by rhaxma

2023-01-02 22:03 UTC, Blaumaus commented on src/project/dto/project.dto.ts
> +  GREATER_THAN = 'greater_than',
Can you also add GREATER_EQUAL_THAN (>=) and LESS_EQUAL_THAN (<=)?

2023-01-02 22:06 UTC, rhaxma commented on src/project/dto/project.dto.ts
> +  GREATER_THAN = 'greater_than',
Yes, of course.

2023-01-02 22:09 UTC, Blaumaus requested changes

2023-01-02 22:09 UTC, Blaumaus commented on src/analytics/analytics.service.ts
> +  }
you can use this instead:
```suggestion
    return await redis.countKeysByPattern(`hb:${pid}:*`)
  }
```

2023-01-02 22:09 UTC, Blaumaus commented on src/auth/auth.controller.ts
> +      const ua = UAParser(userAgent)
this:
```javascript
      const ua = UAParser(userAgent)
      const br = ua.browser.name || 'unknown'
      const dv = ua.device.type || 'desktop'
      const os = ua.os.name || 'unknown'
      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
      const cc =
        ct.getCountryForTimezone(tz)?.id ||
        (headers['cf-ipcountry'] === 'XX' ? 'NULL' : headers['cf-ipcountry'])
      const country = ct.getCountry(cc)?.name || 'unknown'
```

should be put into the `if (user.isTelegramChatIdConfirmed) {` code block.

2023-01-02 22:09 UTC, Blaumaus commented on src/tg-integration/tg.update.ts
> +          project.alertIfOnlineUsersExceeds ? 'seted' : 'not seted'
```suggestion
          project.alertIfOnlineUsersExceeds ? 'set' : 'not set'
```

2023-01-02 22:09 UTC, Blaumaus commented on src/tg-integration/tg.update.ts
> +          project.isAdditionalAlertEnabled ? 'seted' : 'not seted'
```suggestion
          project.isAdditionalAlertEnabled ? 'set' : 'not set'
```

2023-01-02 22:22 UTC, rhaxma commented on src/analytics/analytics.service.ts
> +  }
No, because this function does not exist.

2023-01-03 05:32 UTC, Blaumaus commented on src/analytics/analytics.service.ts
> +  }
@rhaxma fyi it does https://github.com/Swetrix/swetrix-api/blob/main/src/common/constants.ts#L17

2023-01-03 05:32 UTC, Blaumaus commented on src/analytics/analytics.service.ts
> +  }
fixed it at https://github.com/Swetrix/swetrix-api/pull/92/commits/ea583c23666972abdd39e64b5ffb15059f7318c9

2023-01-03 18:06 UTC, Blaumaus approved these changes

2023-01-03 18:06 UTC, merged